server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codersparks/coiledcloud-config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

